name: Package and push to registry repo
on:
  push:
    tags: [v*]

env:
  # the repository to which to push the release version
  # usually a fork of typst/packages (https://github.com/typst/packages/)
  # that you have push privileges to
  REGISTRY_REPO: npikall/typst-packages
  # the path within that repo where the "<name>/<version>" directory should be put
  # for the Typst package registry, keep this as is
  PATH_PREFIX: packages/preview
  PKG_NAME: rubber-article

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Probe runner package cache
        uses: awalsh128/cache-apt-pkgs-action@v1
        with:
          packages: cargo
          version: 1.0

      - name: Install just from crates.io
        uses: baptiste0928/cargo-install@v3
        with:
          crate: just

      - name: Setup typst
        uses: typst-community/setup-typst@v3
        with:
          typst-version: latest

      - name: Setup Go and gotpm
        uses: actions/setup-go@v6
        with:
          go-version: "1.26"
      - run: go install github.com/npikall/gotpm@latest

      - name: Build package
        run: |
          just package out

      - name: Checkout package registry
        uses: actions/checkout@v4
        with:
          repository: ${{ env.REGISTRY_REPO }}
          token: ${{ secrets.REGISTRY_TOKEN }}
          path: typst-packages

      - name: Release package
        run: |
          PKG_VERSION="$(gotpm bump --show-current)"
          mkdir -p "typst-packages/${{ env.PATH_PREFIX }}/${{ env.PKG_NAME }}"
          mv "out/local/${{ env.PKG_NAME }}/${PKG_VERSION}" "typst-packages/${{ env.PATH_PREFIX }}/${{ env.PKG_NAME }}"
          rmdir "out/local/${{ env.PKG_NAME }}"
          rmdir out/local
          rmdir out

          GIT_USER_NAME="$(git log -1 --pretty=format:'%an')"
          GIT_USER_EMAIL="$(git log -1 --pretty=format:'%ae')"

          cd typst-packages
          git config user.name "${GIT_USER_NAME}"
          git config user.email "${GIT_USER_EMAIL}"
          git checkout -b "${{ env.PKG_NAME }}-${PKG_VERSION}"
          git add .
          git commit -m "${{ env.PKG_NAME }}:${PKG_VERSION}"
          git push --set-upstream origin "${{ env.PKG_NAME }}-${PKG_VERSION}"
